chore: add extract all authors methods
NodeSecure/authors pull request #5
Opened 2021-12-06 21:55 UTC by Kawacrepe

2021-12-07 09:14 UTC, tony-go commented
Yo @Kawacrepe 👋 

WDYT about adding a few tests?

2021-12-07 09:29 UTC, Kawacrepe commented
Hey @tony-go it's on my todo list, I just didn't know if my PR was correct and if it would have been better if someone else give an eye on the repository, so I wanted feedback :)

2021-12-07 19:09 UTC, fraxken commented on index.d.ts
> +export function extractAllAuthorsFromLibrary(library: Scanner.Payload): Maintainer[] | [];
Need a new line at the end

2021-12-07 19:16 UTC, fraxken requested changes

2021-12-07 19:16 UTC, fraxken commented on src/index.js
> +      }
`authors.push(...authorsFound);`

No need to execute a for iteration.

2021-12-07 19:16 UTC, fraxken commented on src/index.js
> +      }
Also if authorsFound is returned "empty" no need to protect with `if` condition.

2021-12-13 18:10 UTC, fraxken commented
Could be useful to add UT not just for the main entry point but also for functions in leveinstein etc.

2021-12-14 07:57 UTC, Kawacrepe commented
I added some UT on internal functions which helped me to find a bug in my implementation (if there were the same author in maintainer + publisher I didn't saved `version` & `at` properties).

2021-12-14 16:01 UTC, merged