Feat tag specific authors
NodeSecure/authors pull request #7
Opened 2022-02-08 22:15 UTC by Kawacrepe

2022-02-10 11:27 UTC, fraxken requested changes

2022-02-10 11:27 UTC, fraxken commented on index.d.ts
> +export function extractAllAuthorsFromLibrary(library: Scanner.Payload): authorsResponse
Missing argument here no ?

2022-02-10 11:27 UTC, fraxken commented on src/index.js
> +  if (Object.keys(flags).length === 0) {
Why Object.keys is flags is an Array ?

2022-02-10 11:27 UTC, fraxken commented on src/index.js
> +function formatResponse({ author, maintainers, publishers, packageName = null }) {
Maybe add an option argument and destruct it in the function.

2022-02-10 11:27 UTC, fraxken commented on src/levenshtein.js
> +        if (packageName) {
Avoid coercion here (not clear to me). I guess you mean:

```js
if (typeof packageName === "string") {
}
```

2022-04-02 12:27 UTC, Kawacrepe commented
I updated this PR according to your review in "authors", discord channel.

The most notable changes are:
- we can pass an array of flaggedAuthors.
- `extractAndOptimizeUsers` is removed.
-  the new payload follows this schema.
```javascript
[
  {
    {
    name: "Blake Embrey",
    email: "hello@blakeembrey.com",
    flagged: true,
    packages: [
      {
        homepage: "https://github.com/blakeembrey/array-flatten",
        spec: "array-flatten",
        versions: "3.0.0",
        isPublishers: false
      },
      {
        homepage: "https://github.com/pillarjs/path-to-regexp#readme",
        spec: "path-to-regexp",
        versions: "6.2.0",
        isPublishers: true
      }
  }
]
```

2022-04-02 13:48 UTC, fraxken commented on README.md
> +// [
Il y a pas un soucis sur l'exemple ?

2022-04-02 14:51 UTC, Kawacrepe commented on README.md
> +// [
Effectivement! les flags

2022-04-02 17:17 UTC, fraxken commented
The index.d.ts file should be moved to `./src` i think.

2022-04-03 10:19 UTC, fraxken approved these changes
LGTM

2022-04-03 13:10 UTC, merged